### ISSUE TITLE
wlxjury cannot not start in Vagrant box with Configuration error

### ISSUE THREAD

**Issue by JeanFred** [intracer/wlxjury#68]
After fresh provisioning, `wlxjury` does not start.

Steps to reproduce:
1. `vagrant up`
2. `vagrant ssh`
3. `sudo wlxjury start`
```
Configuration error: Configuration error[application.conf @ file:/usr/share/wlxjury/conf/application.conf: 40: Could not resolve substitution to a value: ${COMMONS_PASSWORD}]
	at play.api.Configuration$.configError(Configuration.scala:178)
	at play.api.Configuration$.load(Configuration.scala:103)
	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ file:/usr/share/wlxjury/conf/application.conf: 40: Could not resolve substitution to a value: ${COMMONS_PASSWORD}
	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
	at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:74)
	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:59)
	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:37)
	at play.api.Configuration$.load(Configuration.scala:99)
	... 4 more
```

**Comment by intracer** [comment]
I still have not decided on how to ease this configuration.

you can edit `conf/application.conf`

and substitute values

```
commons.user = ${COMMONS_USER}
commons.password = ${COMMONS_PASSWORD}
db.default.username = ${WLXJURY_DB_USER}
db.default.password = ${WLXJURY_DB_PASSWORD}

```
or you can set environment variables 
`COMMONS_USER, COMMONS_PASSWORD, WLXJURY_DB_USER, WLXJURY_DB_PASSWORD`

**Comment by intracer** [comment]
actually commons.user  and commons.password are not needed, so I commented them out

**Comment by intracer** [comment]
Resolved. Still need to create root admin user
